---
apiVersion: linkerd.io/v1alpha2
kind: ServiceProfile
metadata:
  name: chaos-server.default.svc.cluster.local
  namespace: default
spec:
  routes:
    - condition:
        method: GET
        pathRegex: /api
      name: GET /api
      isRetryable: false
      timeout: 2000ms
